### ISSUE TITLE
Vertical mode

### ISSUE THREAD

**Issue by AndrewHaglund** [zenzoa/rainblocks#2]
I am loving this game and so thankful to have a good falling block game on Playdate! I started playing [Paper Pilot](https://play.date/games/paper-pilot/) and loved how they used the screen in portrait/vertical orientation.

I wonder if a portrait/vertical mode would be possible in Rainblocks? It would make the bricks much bigger and easier to see (since the Playdate screen is so squat). Either way, wanted to toss out the idea and say thanks for making such a cool game. I love the sound and visual style.

**Comment by zenzoa** [comment]
Thanks! Vertical mode looks very cool, but sadly I don't have the time to add new features to Rainblocks at the moment
